import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { AssetKey } from "./assetCatalog";

type Box = {
  x: number;
  y: number;
  width: number;
  height: number;
};

type ParsedSvg = {
  viewBox: string;
  body: string;
};

type GeneratedManifestEntry = {
  assetKey: AssetKey;
  id: string;
  provider: "generated-openmoji-inspired";
  collection: "openmoji-inspired";
  style: "color";
  label: string;
  concepts: string[];
  svgPath: string;
  source: "ai-svg-generator" | "deterministic-svg-generator";
  styleReference: "OpenMoji color SVG";
  license: "project-generated";
  attribution: "Generated by finalwhite";
  generatedAt: string;
  model?: string;
};

type GeneratedManifest = {
  generatedAt: string;
  provider: "generated-openmoji-inspired";
  collection: "openmoji-inspired";
  style: "color";
  source: "ai-svg-generator" | "deterministic-svg-generator" | "mixed";
  styleReference: "OpenMoji color SVG";
  total: number;
  entries: GeneratedManifestEntry[];
};

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const generatedRoot = path.join(root, "assets", "generated", "openmoji-inspired");
const generatedSvgDir = path.join(generatedRoot, "color", "svg");
const manifestPath = path.join(generatedRoot, "manifest.json");
const svgCache = new Map<string, ParsedSvg>();
let manifestCache: GeneratedManifest | undefined;

function normalize(value: string): string {
  return value
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .normalize("NFKD")
    .replace(/[^\w\s-]/g, " ")
    .replace(/_/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();
}

function slug(value: string): string {
  const normalized = normalize(value).replace(/\s+/g, "-").replace(/-+/g, "-");
  return normalized || "generated-concept";
}

function titleCase(value: string): string {
  return normalize(value)
    .split(/\s+/)
    .filter(Boolean)
    .map((word) => `${word[0]?.toUpperCase() ?? ""}${word.slice(1)}`)
    .join(" ");
}

function conceptsFor(key: string, label?: string): string[] {
  return [...new Set([key, label ?? ""].flatMap((value) => normalize(value).split(/\s+/)).filter((word) => word.length > 2))];
}

function generatedSvgRelativePath(assetKey: string): string {
  return `assets/generated/openmoji-inspired/color/svg/${slug(assetKey)}.svg`;
}

function generatedSvgPath(assetKey: string): string {
  return path.join(generatedSvgDir, `${slug(assetKey)}.svg`);
}

function emptyManifest(): GeneratedManifest {
  return {
    generatedAt: new Date().toISOString(),
    provider: "generated-openmoji-inspired",
    collection: "openmoji-inspired",
    style: "color",
    source: "mixed",
    styleReference: "OpenMoji color SVG",
    total: 0,
    entries: [],
  };
}

function loadManifest(): GeneratedManifest {
  if (manifestCache) return manifestCache;
  if (!existsSync(manifestPath)) {
    manifestCache = emptyManifest();
    return manifestCache;
  }
  manifestCache = JSON.parse(readFileSync(manifestPath, "utf8")) as GeneratedManifest;
  return manifestCache;
}

function writeManifest(manifest: GeneratedManifest): void {
  mkdirSync(generatedRoot, { recursive: true });
  const sorted = manifest.entries.slice().sort((a, b) => a.assetKey.localeCompare(b.assetKey));
  const generatedAt = new Date().toISOString();
  const nextManifest = {
    ...manifest,
    generatedAt,
    total: sorted.length,
    entries: sorted,
  };
  writeFileSync(
    manifestPath,
    `${JSON.stringify(nextManifest, null, 2)}\n`,
    "utf8",
  );
  manifestCache = nextManifest;
}

export function validateGeneratedSvg(svg: string): void {
  const lower = svg.toLowerCase();
  if (!lower.includes("<svg") || !lower.includes("</svg>")) {
    throw new Error("Generated SVG must contain a complete <svg> document.");
  }
  if (svg.length > 40_000) {
    throw new Error("Generated SVG is too large for the asset fallback path.");
  }
  if (/<script\b/i.test(svg) || /\son[a-z]+\s*=/i.test(svg)) {
    throw new Error("Generated SVG must not contain scripts or event handlers.");
  }
  if (/\b(?:href|xlink:href)\s*=\s*["'](?:https?:|data:|file:)/i.test(svg)) {
    throw new Error("Generated SVG must not reference external or embedded images.");
  }
  if (!/\sviewBox="0 0 72 72"/i.test(svg)) {
    throw new Error('Generated SVG must use viewBox="0 0 72 72".');
  }
  if (!/stroke\s*=\s*["'](?:#?111111|#?111|#?000000|#?000|black)["']/i.test(svg)) {
    throw new Error("Generated SVG must include bold black OpenMoji-style outlines.");
  }
}

function parseSvg(svg: string): ParsedSvg {
  const viewBox = svg.match(/\sviewBox="([^"]+)"/)?.[1] ?? "0 0 72 72";
  const body = svg
    .replace(/<\?xml[\s\S]*?\?>/g, "")
    .replace(/<!doctype[\s\S]*?>/gi, "")
    .replace(/<svg\b[^>]*>/i, "")
    .replace(/<\/svg>\s*$/i, "")
    .trim();

  if (!body) {
    throw new Error("Generated SVG is empty.");
  }
  return { viewBox, body };
}

function symbolFor(concepts: string[]): string {
  const text = concepts.join(" ");
  if (/\b(?:cell|cells|biology|bio|gene|genetic|genomics|dna|epigenetic)\b/.test(text)) return "cell";
  if (/\b(?:switch|toggle|control|factor|activate|activation|reprogram)\b/.test(text)) return "switch";
  if (/\b(?:lab|medicine|drug|trial|clinical|vial|test)\b/.test(text)) return "lab";
  if (/\b(?:fund|funding|money|capital|raise|valuation|investor)\b/.test(text)) return "capital";
  if (/\b(?:ai|brain|model|intelligence|neural)\b/.test(text)) return "ai";
  if (/\b(?:team|founder|leader|people|group)\b/.test(text)) return "team";
  if (/\b(?:platform|pipeline|process|workflow|system|engine)\b/.test(text)) return "system";
  if (/\b(?:security|safe|risk|protect|shield)\b/.test(text)) return "shield";
  if (/\b(?:cloud|server|database|storage|compute)\b/.test(text)) return "infra";
  return "concept";
}

function shapeMarkup(symbol: string): string {
  switch (symbol) {
    case "cell":
      return `
        <path d="M19 38 C17 25 28 15 41 17 C55 19 61 31 56 43 C51 56 36 61 25 53 C21 50 20 45 19 38 Z" fill="#92D36E" stroke="#111111" stroke-width="3" stroke-linejoin="round"/>
        <circle cx="38" cy="38" r="10" fill="#B28DFF" stroke="#111111" stroke-width="3"/>
        <path d="M30 30 C34 25 43 25 47 31 M28 48 C35 54 47 51 51 43" fill="none" stroke="#111111" stroke-width="2.4" stroke-linecap="round"/>`;
    case "switch":
      return `
        <rect x="13" y="18" width="46" height="36" rx="9" fill="#FFE66D" stroke="#111111" stroke-width="3"/>
        <line x1="24" y1="28" x2="24" y2="44" stroke="#111111" stroke-width="3" stroke-linecap="round"/>
        <line x1="48" y1="28" x2="48" y2="44" stroke="#111111" stroke-width="3" stroke-linecap="round"/>
        <circle cx="24" cy="35" r="6" fill="#FFFFFF" stroke="#111111" stroke-width="3"/>
        <circle cx="48" cy="37" r="6" fill="#8EC5FF" stroke="#111111" stroke-width="3"/>`;
    case "lab":
      return `
        <path d="M30 12 H43 M34 12 V29 L22 53 C20 57 23 61 28 61 H46 C51 61 54 57 52 53 L39 29 V12" fill="#CDB4DB" stroke="#111111" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>
        <path d="M27 48 H48" stroke="#111111" stroke-width="3" stroke-linecap="round"/>
        <circle cx="32" cy="54" r="2.5" fill="#FFFFFF" stroke="#111111" stroke-width="1.8"/>
        <circle cx="43" cy="53" r="2.5" fill="#FFFFFF" stroke="#111111" stroke-width="1.8"/>`;
    case "capital":
      return `
        <path d="M26 20 C29 12 43 12 46 20 L54 53 C55 58 52 62 47 62 H25 C20 62 17 58 18 53 Z" fill="#8FCD72" stroke="#111111" stroke-width="3" stroke-linejoin="round"/>
        <path d="M28 21 H44 M30 31 C35 27 45 29 44 36 C43 44 30 39 29 47 C29 54 41 55 46 50" fill="none" stroke="#111111" stroke-width="3" stroke-linecap="round"/>
        <line x1="37" y1="27" x2="37" y2="55" stroke="#111111" stroke-width="2.4" stroke-linecap="round"/>`;
    case "ai":
      return `
        <path d="M23 28 C19 16 34 10 42 18 C51 18 57 27 54 36 C60 44 52 57 41 53 C34 61 20 55 23 44 C14 40 15 29 23 28 Z" fill="#B28DFF" stroke="#111111" stroke-width="3" stroke-linejoin="round"/>
        <circle cx="31" cy="34" r="3" fill="#FFFFFF" stroke="#111111" stroke-width="2"/>
        <circle cx="43" cy="34" r="3" fill="#FFFFFF" stroke="#111111" stroke-width="2"/>
        <path d="M30 45 C34 48 41 48 45 44" fill="none" stroke="#111111" stroke-width="2.4" stroke-linecap="round"/>`;
    case "team":
      return `
        <circle cx="36" cy="23" r="9" fill="#FFD166" stroke="#111111" stroke-width="3"/>
        <circle cx="22" cy="31" r="7" fill="#9BD5FF" stroke="#111111" stroke-width="3"/>
        <circle cx="50" cy="31" r="7" fill="#9BD5FF" stroke="#111111" stroke-width="3"/>
        <path d="M18 59 C20 45 52 45 54 59 Z" fill="#8EC5FF" stroke="#111111" stroke-width="3" stroke-linejoin="round"/>
        <path d="M11 59 C13 50 30 49 33 59 M39 59 C42 49 59 50 61 59" fill="#CDB4DB" stroke="#111111" stroke-width="3" stroke-linejoin="round"/>`;
    case "system":
      return `
        <rect x="11" y="22" width="16" height="16" rx="4" fill="#8EC5FF" stroke="#111111" stroke-width="3"/>
        <rect x="45" y="22" width="16" height="16" rx="4" fill="#FFE66D" stroke="#111111" stroke-width="3"/>
        <rect x="28" y="47" width="16" height="16" rx="4" fill="#9EE7C5" stroke="#111111" stroke-width="3"/>
        <path d="M27 30 H45 M35 38 V47 M50 38 L42 47" fill="none" stroke="#111111" stroke-width="3" stroke-linecap="round"/>`;
    case "shield":
      return `
        <path d="M36 10 L57 18 V32 C57 47 47 58 36 63 C25 58 15 47 15 32 V18 Z" fill="#8EC5FF" stroke="#111111" stroke-width="3" stroke-linejoin="round"/>
        <path d="M26 36 L33 43 L48 27" fill="none" stroke="#111111" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>`;
    case "infra":
      return `
        <path d="M21 45 C11 45 9 33 18 30 C18 19 31 14 39 22 C47 18 57 24 56 34 C64 36 63 45 54 45 Z" fill="#9BD5FF" stroke="#111111" stroke-width="3" stroke-linejoin="round"/>
        <rect x="21" y="49" width="30" height="12" rx="3" fill="#FFFFFF" stroke="#111111" stroke-width="3"/>
        <circle cx="29" cy="55" r="2" fill="#111111"/>
        <circle cx="36" cy="55" r="2" fill="#111111"/>`;
    case "concept":
    default:
      return `
        <path d="M26 44 C19 40 17 29 22 21 C28 11 44 11 50 21 C55 30 51 40 44 44 V50 H26 Z" fill="#FFE66D" stroke="#111111" stroke-width="3" stroke-linejoin="round"/>
        <path d="M28 57 H42 M30 50 H40" stroke="#111111" stroke-width="3" stroke-linecap="round"/>
        <circle cx="36" cy="29" r="5" fill="#FFFFFF" stroke="#111111" stroke-width="2.4"/>`;
  }
}

function createGeneratedSvg(input: { key: string; label?: string }): string {
  const concepts = conceptsFor(input.key, input.label);
  const symbol = symbolFor(concepts);
  return `<svg xmlns="http://www.w3.org/2000/svg" width="72" height="72" viewBox="0 0 72 72">
  <title>${titleCase(input.label || input.key)}</title>
  <g fill="none" stroke-linecap="round" stroke-linejoin="round">
    ${shapeMarkup(symbol)}
  </g>
</svg>`;
}

function ensureGeneratedAsset(input: { key: AssetKey; label?: string }): GeneratedManifestEntry {
  const manifest = loadManifest();
  const existing = manifest.entries.find((entry) => entry.assetKey === input.key);
  if (existing && existsSync(path.join(root, existing.svgPath))) return existing;

  mkdirSync(generatedSvgDir, { recursive: true });
  const svg = createGeneratedSvg(input);
  validateGeneratedSvg(svg);
  const svgPath = generatedSvgPath(input.key);
  writeFileSync(svgPath, `${svg}\n`, "utf8");

  const entry: GeneratedManifestEntry = {
    assetKey: input.key,
    id: `generated-openmoji-inspired.${slug(input.key)}`,
    provider: "generated-openmoji-inspired",
    collection: "openmoji-inspired",
    style: "color",
    label: titleCase(input.label || input.key),
    concepts: conceptsFor(input.key, input.label),
    svgPath: generatedSvgRelativePath(input.key),
    source: "deterministic-svg-generator",
    styleReference: "OpenMoji color SVG",
    license: "project-generated",
    attribution: "Generated by finalwhite",
    generatedAt: new Date().toISOString(),
  };

  writeManifest({
    ...manifest,
    entries: [...manifest.entries.filter((item) => item.assetKey !== input.key), entry],
  });
  svgCache.delete(entry.assetKey);
  return entry;
}

export function findGeneratedSvgAsset(key: AssetKey): GeneratedManifestEntry | null {
  const manifest = loadManifest();
  const entry = manifest.entries.find((item) => item.assetKey === key);
  if (!entry || !existsSync(path.join(root, entry.svgPath))) return null;
  return entry;
}

export function writeGeneratedSvgAsset(input: {
  key: AssetKey;
  label?: string;
  svg: string;
  source: GeneratedManifestEntry["source"];
  model?: string;
}): GeneratedManifestEntry {
  validateGeneratedSvg(input.svg);
  mkdirSync(generatedSvgDir, { recursive: true });
  const svgPath = generatedSvgPath(input.key);
  writeFileSync(svgPath, `${input.svg.trim()}\n`, "utf8");

  const entry: GeneratedManifestEntry = {
    assetKey: input.key,
    id: `generated-openmoji-inspired.${slug(input.key)}`,
    provider: "generated-openmoji-inspired",
    collection: "openmoji-inspired",
    style: "color",
    label: titleCase(input.label || input.key),
    concepts: conceptsFor(input.key, input.label),
    svgPath: generatedSvgRelativePath(input.key),
    source: input.source,
    styleReference: "OpenMoji color SVG",
    license: "project-generated",
    attribution: "Generated by finalwhite",
    generatedAt: new Date().toISOString(),
    model: input.model,
  };
  const manifest = loadManifest();
  const nextEntries = [...manifest.entries.filter((item) => item.assetKey !== input.key), entry];
  const source =
    nextEntries.every((item) => item.source === "ai-svg-generator")
      ? "ai-svg-generator"
      : nextEntries.every((item) => item.source === "deterministic-svg-generator")
        ? "deterministic-svg-generator"
        : "mixed";

  writeManifest({
    ...manifest,
    source,
    entries: nextEntries,
  });
  svgCache.delete(entry.assetKey);
  return entry;
}

function loadGeneratedSvg(entry: GeneratedManifestEntry): ParsedSvg {
  if (svgCache.has(entry.assetKey)) {
    const cached = svgCache.get(entry.assetKey);
    if (cached) return cached;
  }

  const filePath = path.join(root, entry.svgPath);
  const svg = readFileSync(filePath, "utf8");
  validateGeneratedSvg(svg);
  const parsed = parseSvg(svg);
  svgCache.set(entry.assetKey, parsed);
  return parsed;
}

function rough(seed: number, amount = 1.2): number {
  return Math.sin(seed * 9.713 + 5.3) * amount;
}

export function renderGeneratedSvgAsset(input: {
  key: AssetKey;
  label?: string;
  box: Box;
  progress: number;
  opacity: number;
  seed: number;
  clipId: string;
}): string {
  const entry = ensureGeneratedAsset({ key: input.key, label: input.label });
  const svg = loadGeneratedSvg(entry);
  const scale = Math.min(input.box.width, input.box.height) / 100;
  const size = 100 * scale;
  const x = input.box.x + (input.box.width - size) / 2 + rough(input.seed);
  const y = input.box.y + (input.box.height - size) / 2 + rough(input.seed + 11);
  const revealWidth = 100 * Math.max(0, Math.min(1, input.progress));
  const clipId = `${input.clipId}_generated_openmoji`;

  return `
    <defs>
      <clipPath id="${clipId}">
        <rect x="0" y="0" width="${revealWidth}" height="100"/>
      </clipPath>
    </defs>
    <g transform="translate(${x} ${y}) scale(${scale})" opacity="${input.opacity}" filter="url(#softShadow)" data-icon="${entry.id}" data-provider="${entry.provider}">
      <g clip-path="url(#${clipId})">
        <svg x="0" y="0" width="100" height="100" viewBox="${svg.viewBox}">
          ${svg.body}
        </svg>
      </g>
    </g>`;
}

export function generateSvgAsset(input: { key: AssetKey; label?: string }): GeneratedManifestEntry {
  return ensureGeneratedAsset(input);
}
